name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ebb25a0a27b9c2e8e8b16bca13c34299f90c1ca9e2b84d0571c722dfbdc3850"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
