name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ba3818535379bf054fe55a3f750357bcab9f0265645c950483ad65cbc053cf4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
