name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09399d2fbd03cdfa8d3d6b3af19a8e14558767d2f37e3631771de3cbcfe7c4e7"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
