name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c24cd7257953c3677aeb0fa0d28abdbf04de5e2cd20799cc2082c6f158b0538a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
