name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21920a9bc32e9fa6146aaea2cae9f2f89d5e9f3e6091a1cce44fd6cded726067"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
