name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdcec12193964fbc1af4bfd7f5b3fb65576352f656256eca2cfc21cff9b8b2ba"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
