name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc64d70b7eff2a3b1cc6c6c2c0f39d5f94b9458899edbeb692baacefa9df42ec"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
