name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f77bdb5e7923ff12a7c9e3870b913e21153edb6c467f9aa96eb013d05b7ad46e"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
