name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "737e95c1349f690f54d3c3bf69eda1d21bd776a8efd3dc7405df47b7da2c455f"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
