name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494635ce4a252b73d4029b8ccef80a004593487db52202dd862ca2fac6f9d5a3"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
