name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a85222b545b969b68ea8dc9c9a61b03ffc63e09d08ded9be58d537510a33cafb"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
