name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183b9528f6cdbe05a57983c474d08feea23ab0025c5b353b47bdbbbf56fe08a4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
