name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b155ce6a9eb9cec6c81618deddfc5a2e9f2f84fb13fbd286ae3116d58751617e"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
