name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96b2e3be1efac4d6d5c84dd4715077f60d5485fb3dae364d79f1c7479114fe40"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
