name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45373e0b1a71b375d6333b56c479a60b914bcc1178b700942f3bc9e8996ea08d"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
