name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eec95fa63f30c2476ab03f3beea8013bc3e694f00ebe0ca8d969e57145a82831"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
