name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34a17afb1b9c9a7a500b69720ca51c8f8b31d824d1bf2e0ccc752a50643a5f19"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.4"]
