name = "connecticut"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10b72633cd32e0247e4fd9437ef9ddb128d5fb05a8bfb3cb78c035750e061072"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
