name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c6c8695c5f93b9678ff9981718faf1ac655eab15d9418536ab723f491e5fbc"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20"]
