name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113f3120586004723d040260f86175a0d487a5ad35c8fe7882108727660dc207"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20"]
