name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e01542251c433f2232c5ff152b8dae0bdd9ef78775eaf151d43413a102f3f749"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20"]
