name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff04e296c9c5eaf7165b41e5796db1f00355ed9755bf8c8184846a6548e95aa"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.3.0"

[options]
acceptable-game-versions = ["1.20"]
