name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6ff946e74a2d223836e5b8c5d0f69d03a161a500b0fc5575e3ef8fbde7f88b5"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.3.0"

[options]
acceptable-game-versions = ["1.20"]
