name = "connecticut"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af2ac2adc0f7694fdce662e762666f8f3f8400a4d7dc37ba957ce2385ead00b6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
