name = "connecticut"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe7c5c457cb64ffc935a09f2e7658449eb4a483f2e7529a5275f288d5629731"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
