name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57442e2e6a23e195be2d89b3dec7cffa2574b570455c9981606fd3a6971ec6c6"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20"]
