name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fefc74241eac0b0ca1adb9e02a3046a255b3568cc6760bbc64d81bb3fc26174"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.3.0"

[options]
acceptable-game-versions = ["1.20"]
