name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a6fcd5e968ba7d33d458d488d725d86e2e6dc817496172b795f31b99ef77a40"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.3.0"

[options]
acceptable-game-versions = ["1.20"]
