name = "connecticut"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b60aa61613a7e190c6ebbb1d70ba3f17d9cd689cf7a400d5647558015a56229"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
