name = "ReconnectedCC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47330b5964f0441dcf55bc4f242bbe97fc8cb8c9fbc6a456bb1472aa0ddf3bdc"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
unsup = "0.3.0"

[options]
acceptable-game-versions = ["1.20"]
