# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      modname:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Mod to update'
        # Default value if no value is explicitly provided
        default: '--all'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      mcversion:
       description: 'Minecraft Version'
       default: '1.21'
       required: true
       
jobs:
  packupdate:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
       go-version: 1.19
      id: go

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Packwiz Update
      run: cd ${{ inputs.mcversion }}/ && packwiz update ${{ inputs.modname }}
